name: StackMob
main: uk.antiperson.stackmob.StackMob
version: ${project.version}
api-version: 1.16
softdepend: [WorldGuard, MythicMobs, ProtocolLib, ClearLag, MyPet, mcMMO, Jobs, Citizens]
author: antiPerson
website: https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance-without-the-sacrifice.29999/
description: A plugin that aims to improve performance by 'stacking' entities together, with attempts to perserve game mechanics.
libraries:
  - net.kyori:adventure-platform-bukkit:4.1.1
  - org.apache.commons:commons-lang3:3.12.0
commands:
  stackmob:
    aliases: [sm]
    permission: stackmob.admin
    description: The main command of stackmob, which allows for manipulation of stacks.
    permission-message: No permission!